# Generated by Django 5.2.17 on 2026-08-10 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LSAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave')], db_index=True, default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='bookings_ls_status_0710fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('child_name', models.CharField(max_length=150)),
                ('child_learning_needs', models.TextField(help_text="Free-text description of the child's learning difficulty/needs")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='bookings_pa_email_85cdea_idx')],
            },
        ),
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(db_index=True)),
                ('session_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('FAILED', 'Payment Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lsa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.lsaprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.parent')),
            ],
            options={
                'indexes': [models.Index(fields=['lsa', 'session_start', 'session_end'], name='bookings_bo_lsa_id_6d0ce2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('session_end__gt', models.F('session_start'))), name='session_end_after_start')],
            },
        ),
    ]
